### ISSUE TITLE
Use Jacoco xml report

### ISSUE THREAD

**Issue by ptsiogas** [ewjoachim/coverage-comment-action#32]
I would like to ask if there are plans to support Jacoco xml report format. This is very usefull for Android & Kotlin multiplatform mobile projects.

**Comment by ewjoachim** [comment]
The problem is that there is no single Python or CLI tool (that I know of) which lets me extract info from most coverage formats. You may have seen my comments in https://github.com/ewjoachim/coverage-comment-action/issues/25: since I realized that there is no such thing as a single standard that works for everyone, I've switched my approach to support only the Python coverage format (in a new repo). If you're willing to find a way to make it work for different usecases, I'll be happy to cooperate with you.

**Comment by ptsiogas** [comment]
You can use [this script](https://github.com/rix0rrr/cover2cover) in order to convert Jacoco report to Cobertura.
I tried it and it seems to work fine. Right now I have implemented this script in my github action but it would be nice if you could embed it in yours.

**Comment by ewjoachim** [comment]
Yeah but that would only cover one usecase. There are [a lot](https://docs.codecov.com/docs/supported-report-formats) of others.

Note: you can also use this script on your workflow before calling the github action :)

**Comment by ptsiogas** [comment]
@ewjoachim ok, I am currently using it i my github action. I am closing this issue.
